"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .containerfile import ContainerFile, ContainerFileTypedDict
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import TypedDict


ContainerFileListResponseObject = Literal["list",]


class ContainerFileListResponseTypedDict(TypedDict):
    data: List[ContainerFileTypedDict]
    first_id: Nullable[str]
    has_more: bool
    r"""True when another page can be fetched by passing `after=last_id`; `last_id` is non-null whenever this is true."""
    last_id: Nullable[str]
    r"""Cursor for the next page (pass as `after`). The last entry’s id, except when the page stopped at the per-request scan bound on hidden bookkeeping objects: then it names the scan position and may not appear in `data`. Null only when `has_more` is false and `data` is empty."""
    object: ContainerFileListResponseObject


class ContainerFileListResponse(BaseModel):
    data: List[ContainerFile]

    first_id: Nullable[str]

    has_more: bool
    r"""True when another page can be fetched by passing `after=last_id`; `last_id` is non-null whenever this is true."""

    last_id: Nullable[str]
    r"""Cursor for the next page (pass as `after`). The last entry’s id, except when the page stopped at the per-request scan bound on hidden bookkeeping objects: then it names the scan position and may not appear in `data`. Null only when `has_more` is false and `data` is empty."""

    object: ContainerFileListResponseObject

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
